version: '3.9'
services:
  webserver:
    build: ./
    ports:
      - "9999:80"
    volumes:
      - ./:/var/www/html
      # - ./run/var:/va r/lib/mysql
      # - ./run/dump/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal
    depends_on:
      - 'db'
  db:
    image: mysql
    ports:
      - "81:3306"
    environment:
      MYSQL_DATABASE: conext
      MYSQL_USER: root
      MYSQL_PASSWORD: 123123
      MYSQL_ROOT_PASSWORD: 123123
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - persistent:/var/lib/mysql
    networks:
      - default
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db:db
    ports:
      - 85:80
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: 123123
      MYSQL_ROOT_PASSWORD: 123123
volumes:
  persistent:
